[workspace]
members = [
    "fahrenheit_celsius_converter", "exercise_1", "exercise_2", "lecture_examples", "fibonacci_number", "exercise_3a",
    "exercise_4", "sorn", "exercise_5", "fib_v3", "exercise_6", ]

resolver = "3"
